[package]
name = "rplayer"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "ui/freya"]


[dependencies]
ffmpeg-next = { version = "7.0" }
tokio = { version = "1.39", features = ["full"] }
image = { version = "0.25" }
orx-priority-queue = "1.2.1"
